### ISSUE TITLE
[Question] Why migrate the brushes to a separate repo?

### ISSUE THREAD

**Issue by ghost** [Sneeds-Feed-and-Seed/SIMP#3]
I noticed the brushes got moved to a separate repo, that's it

might edit the PKGBUILD to include that when I have time, but I have no idea how to actually use PKGBUILD so I'll probably read the man page

**Comment by EverlastingEndeavour** [comment]
The brushes are moved so that anyone can upload new brushes to a repo that isn't as important as the main SIMP repo. You can surely edit PKGBUILD but i think it's better to edit the files for every distro - Makefiles / Meson files.
